README.md

Found that the gir files are a module, so you need --recursive to fetch them.

Update README.md to show recursive clone command

---

Libs/Directory.Build.props

The runtime identifer is not needed at the moment (it is used for self contained deployments). It confuses omnisharp if build with windows (see https://github.com/gircore/gir.core/issues/38#issuecomment-674368380)

Runtime Identifier

---

Libs/GObject/Core/Classes/Object.cs

Fix for #52, allowing us to call protected and private `IntPtr` constructors (we cannot retrieve the Content Area of a Gtk.Dialog as Container's constructors are protected).
Also changes `o.Handle` to `handle`, as `o` is undefined in this call. I've switched `Activator.CreateInstance` to `GetConstructor` as it is more explicit - we could add error handling if the constructor is not found and notify the user?

Fix for non-public constructors

---

WINDOWS.md

Minor update to the windows build instructions.
Adds a troubleshooting section with a few common errors and ways to avoid them.

Add troubleshooting section to WINDOWS.md

---

Generator/Templates/Shared/enum_member.sbntxt
Libs/GLib/Classes/VariantType.cs
Libs/GObject/Classes/Signal.cs
Libs/Gio/Classes/DBusConnection.cs
Samples/DBus/Program.cs
Samples/DBus/SendNotification.cs
Samples/DBus/ShowApplicationsAsync.cs

Enable DBus sample

---

Libs/GObject/Classes/ClosureHelper.cs
Libs/GObject/Classes/Object.cs

Keeps a reference to any delegates we use to avoid upsetting the garbage collector when low on RAM.
The culprits seem to be the following two delegates, which I've gone ahead and fixed:
- `MarshalCallback` in `ClosureHelper.cs`
- `OnFinalized` in `Object.cs`
I'm not finding anything else, but if we do encounter this later the fix is rather straightforward. We can avoid this by holding a strong reference to any delegates we pass to GLib.
Fixes #82

Fix Garbage Collection of Delegates

---

Generator/Gir/GNamespace.cs

The libraries are named e.g. `libgtk-3.0.dylib` on macOS.
I tested with the GTK libraries installed via homebrew, and this fixes the runtime errors I hit while running the sample GTK application.

Generate the correct library names for macOS.

---

Generator/Templates/Shared/helper_dll_import.sbntxt

- Cache library pointers
- Handle unknown libraries gracefully
- Forward given search path to `NativeLibrary.TryLoad`
Fixes #161 
@gircore/coreteam Please test again under windows as this changes the call of `NativeLibrary.TryLoad` to take the search path from the caller.

DllImport: Improvements

---

Generator/Templates/GObject/signal.sbntxt
Generator/Templates/Shared/header.sbntxt
Generator/Templates/Shared/helper.sbntxt

Add xml documentation which explains if each parameter of a method should transfer the ownership or not.
This information makes it easy to write manual code to handle the ownership transfer. See  #78 
Return values are going to be added.

Generator: Add ownership transfer to xml documentation

---

Generator/Factories/ScriptObjectFactory.cs
Generator/TemplateWriter.cs
Generator/Templates/delegate.sbntxt

Only generates a return statement for a delegate if it has a non-void return value. Also changes the name of the returned variable to avoid name conflicts.

Fix delegate return values

---

Libs/GLib-2.0/Records/Bytes.cs
Libs/GLib-2.0/Records/Variant.cs
Libs/GObject-2.0/Classes/Functions.cs
Libs/GObject-2.0/Records/Value.cs
Libs/GObject-2.0/Structs/Type.cs
Repository/Factories/Model/ClassFactory.cs
Repository/Factories/Model/InterfaceFactory.cs
Repository/Factories/Model/MethodFactory.cs
Repository/Factories/Model/RecordFactory.cs
Repository/Factories/Model/UnionFactory.cs
Repository/Services/TypeReferenceResolverService.cs

According to glib documentation [gsize](https://developer.gnome.org/glib/stable/glib-Basic-Types.html#gsize) datatype is dependent on the underlying system architecture (x86 / x64). 
To address those kind of issues C#9 introduces the primitive datatype `nint` `nuint`. See the following blog post for an overview: https://developers.redhat.com/blog/2021/04/27/some-more-c-9/
This PR changes the datatype of `gsize` to `nuint` to reflect the documentation. The alias `GType` resolves into `gsize`. For this reason the code regarding `GType` must be adopted, too.

Use nuint as gsize datatype

---

Generator/Convert.cs
Generator/Extensions/AnyTypeExtension.cs
GirLoader/Output/Model/TypeInformationFactory.cs
Libs/GObject-2.0/Classes/Object.cs
Libs/GObject-2.0/Delegates/ClosureMarshalCallbackWorkaround.cs
Tests/Libs/Gtk-3.0.Tests/ConstructorTest.cs

Unpointed records (value based)
* For non array records in the gir their original record structure must be used.
* For arrays of records in the gir their original record structure must be used inside an array.
Pointed records (pointer based)
* For non array records in the gir a pointer must be used. This could either be an SafeHandle (regular case) or an IntPtr (e.g. in case of free methods).
* For arrays of records always IntPtr[] must be used as arrays of SafeHandles are not supported by the runtime.
The method and delegate generators currently do not differentiate between pointed and unpointed records. To avoid compilation errors those cases are currently passing default values to methods and marked with a TODO flag.
This fixes the window sample.

Generator: Differentiate between pointed / unpointed records

---

src/Generation/GirLoader/Helper/RepositoryDependencyResolver.cs
src/Generation/GirLoader/Output/Namespace.cs
src/Generation/GirLoader/Output/NamespaceFactory.cs
src/Generation/GirLoader/Output/Repository.cs
src/Generation/GirLoader/RepositoryConverter.cs
src/Generation/GirLoader/RepositoryResolver.cs

This is necessary to be able to create unit tests for the generator to create test scenarios.
The properties are set to init only. An update of the properties after the object creation is not possible like before.

Allow Namespace class to be filled from a caller.

---

src/Generation/Generator/Templates/native.safehandle.sbntxt
src/Libs/GLib-2.0/Classes/MarshalHelper.cs
src/Libs/GObject-2.0/Records/Closure.cs
src/Libs/Gst-1.0/Classes/Pad.cs
src/Libs/Gst-1.0/Records/Message.cs
src/Libs/Gst-1.0/Records/Structure.cs
src/Libs/Gst-1.0/Records/TagList.cs
src/Libs/GstPbutils-1.0/Classes/Global.cs
src/Libs/GstVideo-1.0/Interfaces/Navigation.cs

I update where can
- `Marshal.SizeOf(Type)` replaced with `Marshal.SizeOt<T>()`
- `Marshal.PtrToStructure(IntrPtr, Type)` replaced with `Marshal.PtrToStructure<T>(IntPtr)`
- `Marshal.StructureToPtr(object, IntPtr, bool)` replaced with `Marshal.StructureToPtr<T>(T, IntPtr, bool)`
This update change codegeneration piece and commented code,
since in case somebody willing to make that code works,
I would like that this part would not slip between cracks.

Make code a bit more NativeAOT friendly

---

src/Generation/Generator3/Generation/Constants/Model.cs
src/Generation/Generator3/Model/Public/Constant.cs
src/Generation/GirModel/GirModel.csproj

Validate constants

---

src/Libs/cairo-1.0/Internal/Records/Context.cs
src/Libs/cairo-1.0/Records/Context.cs

- Move the native methods into the Internal namespace to be more consistent with normal generated bindings
- Sort into alphabetical order for readability

Refactor the manual Cairo bindings

---

src/Generation/Generator3/Generation/Record/InternalOwnedHandle/InternalOwnedHandleModel.cs
src/Generation/Generator3/Generation/Record/InternalOwnedHandle/InternalOwnedHandleTemplate.cs
src/Generation/Generator3/Generation/Record/InternalOwnedHandle/ReleaseHandleRenderer.cs
src/Libs/cairo-1.0/Internal/Framework/DllImportOverride.cs
src/Libs/cairo-1.0/Internal/Records/Context.cs
src/Libs/cairo-1.0/Internal/Records/ContextOwnedHandle.cs
src/Libs/cairo-1.0/Internal/Records/Device.cs
src/Libs/cairo-1.0/Internal/Records/DeviceOwnedHandle.cs
src/Libs/cairo-1.0/Internal/Records/FontFace.cs
src/Libs/cairo-1.0/Internal/Records/FontFaceOwnedHandle.cs
src/Libs/cairo-1.0/Internal/Records/FontOptions.cs
src/Libs/cairo-1.0/Internal/Records/FontOptionsOwnedHandle.cs
src/Libs/cairo-1.0/Internal/Records/MatrixOwnedHandle.cs
src/Libs/cairo-1.0/Internal/Records/Path.cs
src/Libs/cairo-1.0/Internal/Records/PathOwnedHandle.cs
src/Libs/cairo-1.0/Internal/Records/Pattern.cs
src/Libs/cairo-1.0/Internal/Records/PatternOwnedHandle.cs
src/Libs/cairo-1.0/Internal/Records/Region.cs
src/Libs/cairo-1.0/Internal/Records/RegionOwnedHandle.cs
src/Libs/cairo-1.0/Internal/Records/ScaledFont.cs
src/Libs/cairo-1.0/Internal/Records/ScaledFontOwnedHandle.cs
src/Libs/cairo-1.0/Internal/Records/Surface.cs
src/Libs/cairo-1.0/Internal/Records/SurfaceOwnedHandle.cs

- For foreign records, ReleaseHandle() is marked partial and not implemented, so the manual bindings are required to fill it in manually with the appropriate cleanup function
- Implement ReleaseHandle() for all of the foreign records. Added a constant for the Cairo library name in the DllImportOverride class to avoid duplicated string constants
- The one exception is Cairo.Matrix, which doesn't have a cleanup function since it's a plain C struct that is always allocated and managed by the caller, so I think only MatrixManagedHandle will ever be used.
Related to PR #578

Require a foreign record's OwnedHandle to manually implement ReleaseHandle()

---

src/Libs/cairo-1.0/Internal/Records/FontOptions.cs
src/Libs/cairo-1.0/Internal/Records/Surface.cs
src/Libs/cairo-1.0/Records/FontOptions.cs
src/Libs/cairo-1.0/Records/Surface.cs
src/Tests/Libs/Cairo-1.0.Tests/FontOptionsTest.cs
src/Tests/Libs/Cairo-1.0.Tests/ImageSurfaceTest.cs

- Add bindings for the majority of Cairo.Surface functions. A couple such as 'cairo_surface_set_mime_data' and 'cairo_surface_set_user_data' are skipped, which have more complex lifetime requirements
- Add minimal bindings for FontOptions in order to be able to implement cairo_surface_get_font_options()

Add most of the Cairo.Surface bindings

---

src/Libs/cairo-1.0/Internal/Records/Context.cs
src/Libs/cairo-1.0/Internal/Records/ContextOwnedHandle.cs
src/Libs/cairo-1.0/Internal/Records/Device.cs
src/Libs/cairo-1.0/Internal/Records/DeviceOwnedHandle.cs
src/Libs/cairo-1.0/Internal/Records/FontFace.cs
src/Libs/cairo-1.0/Internal/Records/FontFaceOwnedHandle.cs
src/Libs/cairo-1.0/Internal/Records/FontOptions.cs
src/Libs/cairo-1.0/Internal/Records/FontOptionsOwnedHandle.cs
src/Libs/cairo-1.0/Internal/Records/Path.cs
src/Libs/cairo-1.0/Internal/Records/PathOwnedHandle.cs
src/Libs/cairo-1.0/Internal/Records/Pattern.cs
src/Libs/cairo-1.0/Internal/Records/PatternOwnedHandle.cs
src/Libs/cairo-1.0/Internal/Records/Region.cs
src/Libs/cairo-1.0/Internal/Records/RegionOwnedHandle.cs
src/Libs/cairo-1.0/Internal/Records/ScaledFont.cs
src/Libs/cairo-1.0/Internal/Records/ScaledFontOwnedHandle.cs
src/Libs/cairo-1.0/Internal/Records/Surface.cs
src/Libs/cairo-1.0/Internal/Records/SurfaceOwnedHandle.cs

The Destroy() methods can't use the SafeHandle type. From https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.safehandle?view=net-6.0#what-safehandle-does, this will bump the SafeHandle's refcount and fail because the object is marked as closed (since this is in the Dispose() implementation)
So, these methods have to use a plain IntPtr instead.
Related to #598

Fix errors when closing the Cairo SafeHandle's

---

src/Tests/Libs/Cairo-1.0.Tests/FontOptionsTest.cs
src/Tests/Libs/Cairo-1.0.Tests/ImageSurfaceTest.cs
src/Tests/Libs/Cairo-1.0.Tests/Test.cs
src/Tests/Libs/GLib-2.0.Tests/Records/ExceptionTest.cs
src/Tests/Libs/GLib-2.0.Tests/Records/UnownedHandleTest.cs
src/Tests/Libs/GLib-2.0.Tests/Records/VariantTest.cs
src/Tests/Libs/GLib-2.0.Tests/Records/VariantTypeTest.cs
src/Tests/Libs/GLib-2.0.Tests/Test.cs
src/Tests/Libs/GObject-2.0.Tests/Classes/ParamSpecTest.cs
src/Tests/Libs/GObject-2.0.Tests/Records/ValueTest.cs
src/Tests/Libs/GObject-2.0.Tests/Test.cs
src/Tests/Libs/GdkPixbuf-2.0.Tests/MemoryManagementTest.cs
src/Tests/Libs/GdkPixbuf-2.0.Tests/PropertyTest.cs
src/Tests/Libs/GdkPixbuf-2.0.Tests/Test.cs
src/Tests/Libs/Gio-2.0.Tests/DBusConnectionTest.cs
src/Tests/Libs/Gio-2.0.Tests/Test.cs
src/Tests/Libs/Gtk-3.0.Tests/ConstructorTest.cs
src/Tests/Libs/Gtk-3.0.Tests/PropertyTests.cs
src/Tests/Libs/Gtk-3.0.Tests/SignalTest.cs
src/Tests/Libs/Gtk-3.0.Tests/Test.cs

This enforces the garbage collector to collect all objects which can be freed. This uncovers if an object is freed by the garbage collector which is not freeable anymore.
Fixes #525

Wait for garbage collector to free memory

---

src/GirCore.Logging.props
src/GirCore.Testing.props

- Bump Serilog to 2.11.0
- Bump MSTest.TestAdapter to 2.2.10
- Bump MSTest.TestFramework to 2.2.10

Bump nuget versions

---

src/Libs/cairo-1.0/Internal/Records/Context.cs
src/Libs/cairo-1.0/Records/Context.cs
src/Tests/Libs/Cairo-1.0.Tests/ContextTest.cs

This is a followup to #624 and adds the remaining bindings from https://cairographics.org/manual/cairo-cairo-t.html.
The one exception is `cairo_copy_clip_rectangle_list()`, which probably needs some special wrapping since `cairo_rectangle_list_t` isn't very friendly to expose directly in C#

Add the remaining general Cairo.Context bindings

---

src/Libs/cairo-1.0/Internal/Records/Context.Paths.cs
src/Libs/cairo-1.0/Internal/Records/Context.cs
src/Libs/cairo-1.0/Records/Context.Paths.cs
src/Libs/cairo-1.0/Records/Context.cs
src/Tests/Libs/Cairo-1.0.Tests/ContextTest.cs

Following #590 I've put these into a separate `Context.Paths.cs` file for organization, but the API is still under `Cairo.Context`
This adds everything from https://cairographics.org/manual/cairo-Paths.html, except for `cairo_glyph_path()` which is left until bindings are done for https://cairographics.org/manual/cairo-text.html

Add Cairo.Context bindings related to paths

---

src/Libs/cairo-1.0/Internal/Records/Context.Text.cs
src/Libs/cairo-1.0/Internal/Records/Context.cs
src/Libs/cairo-1.0/Internal/Records/FontFace.cs
src/Libs/cairo-1.0/Internal/Records/ToyFontFace.cs
src/Libs/cairo-1.0/Records/Context.Text.cs
src/Libs/cairo-1.0/Records/Context.cs
src/Libs/cairo-1.0/Records/FontFace.cs
src/Libs/cairo-1.0/Records/ToyFontFace.cs
src/Tests/Libs/Cairo-1.0.Tests/ContextTest.cs
src/Tests/Libs/Cairo-1.0.Tests/FontFaceTest.cs

This adds the methods from https://cairographics.org/manual/cairo-text.html, minus the `cairo_glyph_t` methods which require bindings for additional types.
The methods related to the toy font face API (`cairo_toy_font_face_create()` etc) have also been added

Add Cairo.Context text-related methods

---

src/Libs/cairo-1.0/Internal/Records/ScaledFont.cs
src/Libs/cairo-1.0/Records/ScaledFont.cs
src/Tests/Libs/Cairo-1.0.Tests/ScaledFontTest.cs

This adds the bindings from https://cairographics.org/manual/cairo-cairo-scaled-font-t.html, minus the `cairo_glyph_t` methods which require bindings for additional types.

Add bindings for Cairo.ScaledFont

---

src/Generation/Generator/Renderer/Public/ParameterToNativeExpression/Converter/String.cs
src/Generation/Generator/Renderer/Public/ParameterToNativeExpression/Converter/StringArray.cs

This addresses a couple issues encountered with global functions (#724)
- Raise an error for out string parameters with caller-allocates=true. This occurs for `g_unichar_to_utf8()`, which expects the caller to provide a suitably sized buffer, so I don't think we can safely generate bindings automatically for functions like that
-  String arrays that are a ref/out parameter produce compile errors with the current code and require further work to support. In particular, some functions like `hb_feature_to_string()` seem to incorrectly appear with string array out parameters, but actually behave like `g_unichar_to_utf8()` above and expect a pre-allocated buffer.
- While looking into this, I noticed that string arrays should also be converted to UTF8 strings, matching regular string parameters

Fix a couple issues with string (array) parameters

---

src/Generation/Generator/Renderer/Public/ParameterToNativeExpression/Converter/Enumeration.cs

I think this is an invalid combination in general - either it should be an inout / out parameter if the value can be modified by the native function, or otherwise it should be an array type
With #724 this occurs for two functions:
- `pango_log2vis_get_embedding_levels()`. Here the C documentation indicates that it actually behaves as an in/out parameter
- `gst_buffer_add_video_gl_texture_upload_meta()`. In this case the C API is expecting an array
As `inout` and `out` enums are not currently handled, this was similarly producing incorrect generated code.

Disable enum parameters that have a pointer type but a direction of 'in'

---

src/Libs/cairo-1.0/Internal/ImageSurface.cs
src/Libs/cairo-1.0/Public/ImageSurface.cs
src/Libs/cairo-1.0/cairo-1.0.csproj
src/Tests/Libs/Cairo-1.0.Tests/ImageSurfaceTest.cs

This is used for low-level (via `unsafe`) modification of the image buffer
Note in GtkSharp this was called `DataPtr` because they also had a separate `Data` property that returned a `byte[]` copy (https://github.com/GtkSharp/GtkSharp/blob/develop/Source/Libs/CairoSharp/ImageSurface.cs#L85), but I think calling the property `Data` is better to match the underlying Cairo API

Add binding for cairo_image_surface_get_data()

---

src/Generation/Generator/Renderer/Public/Parameter/From/ArrayRecordParameter.cs
src/Generation/Generator/Renderer/Public/ParameterToNativeExpression/Converter/RecordArray.cs
src/Generation/GirLoader/Input/ArrayType.cs
src/Generation/GirLoader/Output/TypeReferenceFactory.cs

This occurred for `g_dbus_annotation_info_lookup()` which #724 now generates bindings for
- The public type should just be `Gio.DBusAnnotationInfo[]`, not `IntPtr[]`
- If there isn't a parameter that specifies the length, ensure that a null terminated pointer array is provided to the native function
- Fix a typo in the generated code: `DangerousGethandle` -> `DangerousGetHandle`. This code path wasn't being hit previously :)
The generated code for this function was previously:
```
public static string? DbusAnnotationInfoLookup(IntPtr[] annotations, string name)
{
var annotationsNative = annotations.Select(record => record.Handle.DangerousGethandle()).ToArray();
var result = Gio.Internal.Functions.DbusAnnotationInfoLookup(annotationsNative, name);
return …
```

Fix errors with marshalling record array parameters.

---

src/Generation/Generator/Renderer/Public/ParameterToNativeExpression/Converter/String.cs

The default marshalling produces crashes for functions like `pango_skip_space()`, so more investigation is required.
This is related to #724, where a compile error (missing 'ref' keyword) was also produced because the surrounding code only handled 'in' and 'out' strings.
So far, `inout` string parameters only occur for deprecated pango functions.

Disable string parameters with a direction of inout

---

src/Generation/Generator/Generator/Public/Class/ClassFunctions.cs
src/Generation/Generator/Generator/Public/InterfaceImplementation/InterfaceImplementationFramework.cs
src/Libs/GObject-2.0/Internal/GTypeProviderHelper.cs
src/Libs/GObject-2.0/Public/Object.Signals.cs
src/Libs/GObject-2.0/Public/SignalDefinition.cs
src/Libs/GObject-2.0/Public/SignalTSender.cs
src/Libs/GObject-2.0/Public/SignalTSenderTSignalArgs.cs

Detailed signals are providing some kind of filtering for signals.
See: https://docs.gtk.org/gobject/concepts.html#the-detail-argument
Depends on: #741

Support detailed signals

---

src/Generation/Generator/Generator/Public/Class/ClassSignals.cs
src/Generation/Generator/Renderer/Internal/Callback/CallbackCommonHandlerRenderUtils.cs
src/Generation/Generator/Renderer/Public/ReturnTypeToManagedExpression/Converter/PlatformString.cs
src/Generation/Generator/Renderer/Public/ReturnTypeToManagedExpression/Converter/Utf8String.cs
src/Libs/GLib-2.0/Internal/StringHelper.cs
src/Libs/GObject-2.0/Public/Value.cs
src/Tests/Libs/GLib-2.0.Tests/FunctionTest.cs

Simplify string helper

---

src/Libs/GLib-2.0/Public/Dir.cs
src/Tests/Libs/GLib-2.0.Tests/Records/DirTest.cs

Add IDisposable to Glib.Dir

---

src/Generation/Generator/Fixer/Class/InterfaceMethodsCollidingWithClassMethodsFixer.cs
src/Generation/Generator/Fixer/Class/PropertyLikeInterfacePropertyFixer.cs
src/Generation/Generator/Model/Method.cs
src/Generation/Generator/Model/Property.cs
src/Generation/Generator/Renderer/Public/Class/InterfaceProperties/ClassInterfacePropertiesRenderer.Accessor.cs
src/Generation/Generator/Renderer/Public/MethodRenderer.cs

- Avoid naming conflicts for properties. E.g. an interface can have a readonly property but a class can have the same property with read / write access.
- If there are two diffent methods with the same signature on a class / interface they could have different implementations. Using explicit interface implementations allows the user to access the implementation which is wanted.
Fixes: #740

Generator: Use explicit interface implementations

---

src/Libs/GObject-2.0/Public/Value.cs
src/Tests/Libs/GObject-2.0.Tests/Records/ValueTest.cs
src/Tests/Libs/Gio-2.0.Tests/SimpleActionTest.cs

This fixes issues with e.g. accessing the GVariant parameter from the `Gio.SimpleAction::activate` [signal](https://docs.gtk.org/gio/signal.SimpleAction.activate.html), which internally requires going through a GObject.Value

Support using a GLib.Variant in a GObject.Value

---

src/Libs/GObject-2.0/Public/ReturningSignalTSender.cs
src/Libs/GObject-2.0/Public/ReturningSignalTSenderTSignalArgs.cs
src/Libs/GObject-2.0/Public/SignalTSender.cs
src/Libs/GObject-2.0/Public/SignalTSenderTSignalArgs.cs

Rename Signal.Connect parameter

---

src/Generation/Generator/Renderer/Internal/Parameter/From/PrimitiveValueTypeParameter.cs
src/Generation/Generator/Renderer/Public/Parameter/From/PrimitiveValueTypeParameter.cs
src/Generation/Generator/Renderer/Public/Parameter/RenderableParameterFactory.cs
src/Generation/Generator/Renderer/Public/ParameterToNativeExpression/Converter/PrimitiveValueType.cs
src/Generation/Generator/Renderer/Public/ParameterToNativeExpression/Converter/RecordArray.cs
src/Generation/GirLoader/Input/Parameter.cs
src/Generation/GirLoader/Output/SingleParameter.cs
src/Generation/GirLoader/Output/SingleParameterFactory.cs
src/Generation/GirModel/Parameter.cs
src/Libs/Gst-1.0/Public/Application.Static.cs
src/Native/GirTestLib/girtest-primitive-value-type-tester.c
src/Native/GirTestLib/girtest-primitive-value-type-tester.h
src/Tests/Libs/GirTest-0.1.Tests/PrimitiveValueTypeTest.cs

I think this covers all of the possible cases for primitive value types, with the main addition being support for functions with `inout` or `out` primitive value parameters
- Don't generate public bindings for primitive value pointer types that have a direction of `in`. Many occurrences of this in the gir files were actually treating the pointer as an array, but didn't mark it as such in the documentation (e.g. `gdk_pango_layout_get_clip_region()`), so I don't think we can safely generate public bindings for this case.
- Translate `inout` and `out` parameters to 'ref' and 'out' parameters in C#.
- Nullable `out` parameters are just exposed as non-nullable `out` parameters in C#. In C the meaning of null is "ignore the output value", so in C# I think the idiomatic equivalent is to just …

Add more comprehensive support for primitive value type parameters

---

src/Generation/Generator/Model/Member.Disable.cs
src/Generation/Generator/Model/Method.Disable.cs
src/Generation/Generator/Model/Method.cs
src/Generation/Generator/Model/Property.Disable.cs
src/Generation/Generator/Model/Property.cs
src/Generation/Generator/Model/Record.Disable.cs

Lock collections on write access as those methods are not thread safe

---

src/Libs/cairo-1.0/Internal/Context.Paths.cs
src/Libs/cairo-1.0/Internal/Context.Text.cs
src/Libs/cairo-1.0/Internal/FontOptions.cs
src/Libs/cairo-1.0/Internal/ScaledFont.cs
src/Libs/cairo-1.0/Internal/ToyFontFace.cs
src/Libs/cairo-1.0/Public/Context.Paths.cs
src/Libs/cairo-1.0/Public/Context.Text.cs
src/Libs/cairo-1.0/Public/FontOptions.cs
src/Libs/cairo-1.0/Public/ScaledFont.cs
src/Libs/cairo-1.0/Public/ToyFontFace.cs
src/Tests/Libs/Cairo-1.0.Tests/FontOptionsTest.cs

This is largely just a refactoring to make the manual bindings consistent with the generated bindings after #803, using the new string handle classes
For string return values this adds some more type safety over IntPtr, and fixes a couple nullable warnings from the usage of `StringHelper.ToStringUtf8()`. `FontOptions.Variations` should have actually been a nullable string, while `ToyFontFace.Family` is correct to be a non-nullable string.

Update manual Cairo bindings for string parameters

---

src/Generation/Generator/Generator.csproj
src/GirCore.Testing.props
src/Integration/Integration.csproj
src/Libs/GLib-2.0/Internal/NullHandleException.cs
src/Libs/GLib-2.0/Internal/PlatformStringHandle.cs
src/Libs/GLib-2.0/Internal/Utf8StringHandle.cs
src/Libs/GObject-2.0/Public/Value.cs
src/Native/GirTestLib/girtest-property-tester.c
src/Native/GirTestLib/girtest-property-tester.h
src/Native/GirTestLib/girtest-string-tester.c
src/Native/GirTestLib/girtest-string-tester.h
src/Native/GirTestLib/girtest.h
src/Native/GirTestLib/meson.build
src/Tests/Libs/GirTest-0.1.Tests/PropertyTest.cs
src/Tests/Libs/GirTest-0.1.Tests/StringTest.cs
src/Tests/Libs/Gtk-4.0.Tests/PropertyTests.cs

Todo:
- Update nugets
- add unit test to ensure exception is thrown in case of an unexpected null string return for utf8 and platform string. Possible exception name `"StringNullPointerException" / "NullPointerExcception" / "NullPointerConversionException" / NullPointerException<T> / NullHandleException`
- add doc comments to new safe handles

Fix null return of GObject.Value.GetString

---

src/Generation/Generator/Renderer/Internal/Parameter/From/StringParameter.cs
src/Generation/Generator/Renderer/Public/FunctionRenderer.cs
src/Generation/Generator/Renderer/Public/MethodRenderer.cs
src/Generation/Generator/Renderer/Public/ParameterToNativeExpression/Converter/PlatformString.cs
src/Generation/Generator/Renderer/Public/ParameterToNativeExpression/Converter/Utf8String.cs
src/Generation/Generator/Renderer/Public/ParameterToNativeExpression/ParameterToNativeData.cs
src/Native/GirTestLib/girtest-string-tester.c
src/Native/GirTestLib/girtest-string-tester.h
src/Tests/Libs/GirTest-0.1.Tests/StringTest.cs

- The internal functions have a signature such as `out NonNullablePlatformStringUnownedHandle`, corresponding to the native signatures like `const gchar **`
- Introduce a "post-call" expression for parameters, which is used to take the resulting string handle and assign `handle.ConvertToString()` to the original `out string` parameter
- As with primitive value types, optional parameters are just generated as a normal `out` parameter that the caller can ignore with `out var _` if desired
- A direction of inout, or caller-allocates=1, is still not supported due to the issues noted in `ParameterToNativeExpression/Converter/Utf8String.cs`. These are low priority since inout string parameters only occur for deprecated functions, and `g_unichar_to_utf8` is the only function with …

Support string parameters with direction=out

---

src/Generation/Generator/Renderer/Public/Constants/Constants.cs
src/Native/GirTestLib/girtest-constant-tester.h
src/Native/GirTestLib/girtest.h
src/Native/GirTestLib/meson.build
src/Tests/Libs/GirTest-0.1.Tests/ConstantTest.cs

Also added some test coverage to GirTest for generating constants
Fixes: #820

Render constants as 'const' rather than 'static' values

---

src/Generation/Generator/Renderer/Public/ParameterToNativeExpression/Converter/PlatformString.cs
src/Generation/Generator/Renderer/Public/ParameterToNativeExpression/Converter/Utf8String.cs
src/Libs/GLib-2.0/Internal/PlatformStringHandle.cs
src/Libs/GLib-2.0/Internal/StringHelper.cs
src/Libs/GLib-2.0/Internal/Utf8StringHandle.cs
src/Native/GirTestLib/girtest-string-tester.c
src/Native/GirTestLib/girtest-string-tester.h
src/Tests/Libs/GirTest-0.1.Tests/StringTest.cs

If a method takes in a string and ownership is transferred to the method an unowned string is generated as this string is not freed by dotnet and can then be freed by C.
Fixes: #847

Fix string double free bug in case of full ownership transfer

---

src/Generation/Generator/Fixer/Class/PropertyNamedLikeClassFixer.cs
src/Generation/Generator/Model/Property.cs
src/Native/GirTestLib/girtest-property-tester.c
src/Tests/Libs/GirTest-0.1.Tests/PropertyTest.cs

Render properties named like it's containing class instead of disabling them. This adds a suffix to the property name to avoid a conflict with the class name.
Part of #792

Render properties which are named like it's containing class

---

src/Generation/Generator/Fixer/Class/PublicMethodsWithInvalidOutParameterFixer.cs
src/Generation/Generator/Fixer/Classes.cs

Disable methods if they have a caller allocated out parameter with a size parameter with the direction out. The out size parameter does not make sense if the first parameter is caller allocated. In this case the size parameter must be caller allocated, too.
As this can't be fixed during render time the method is disabled completely. To fix this the gir file must be fixed upstream.

Disable method if annotations are wrong

---

src/Generation/Generator/Renderer/Internal/Parameter/Converter/ClassGLibPtrArray.cs
src/Generation/Generator/Renderer/Internal/Parameter/Converter/PointerGLibPtrArray.cs
src/Generation/Generator/Renderer/Internal/Parameter/Converter/PrimitiveValueTypeGLibPtrArray.cs
src/Generation/Generator/Renderer/Internal/Parameter/Converter/RecordGLibPtrArray.cs
src/Generation/Generator/Renderer/Internal/Parameter/Converter/StringGLibPtrArray.cs

This is needed for the gtksourceview bindings (specifically, the completion API, which gets only partially rendered without this, which results in build errors).
I'm not totally certain of the internal -> public conversion so let me know if that looks sketchy. I largely copied it from the interface converter.

Slightly improved support for GPtrArray

---

src/Libs/GObject-2.0/Internal/TypeRegistrar.cs

This just switches to `Debug.WriteLine`, similar to other classes like `ObjectMapper`.
I also searched for other print statements and this seems to be the only one printing to the console, outside of the samples.
Fixes: #844

Avoid printing to the console when registering a GType.

---

src/Generation/Generator/Renderer/Public/ParameterToNativeExpression/Converter/Interface.cs

This could generate nullable warnings from the `as` expression producing null, or from the parameter being nullable. Since interfaces inherit from the `GLib.IHandle` interface, this cast can be avoided by just using its `Handle` property. This is done inline, similar to how class parameters are converted to native parameters.
This reduces the number of warnings in the build from 6552 to 5792

Fix nullable warnings for interface parameters.

---

src/Libs/GLib-2.0/Public/UnhandledException.cs
src/Libs/GObject-2.0/Public/Closure.cs
src/Tests/Libs/GirTest-0.1.Tests/UnhandledExceptionTest.cs

These unhandled exceptions would otherwise immediately terminate the program once they reach the native code boundary. An exception handler lets applications do any logging / message dialogs etc and decide whether they want to terminate the program or attempt to continue.
@cameronwhite I took your initial code and updated it to not use an event. I think this is a simpler approach for now.

Allows to add an exception handler for unhandled exceptions

---

src/Libs/GLib-2.0/Internal/MainLoopSynchronizationContext.cs
src/Libs/GLib-2.0/Public/MainLoop.cs
src/Libs/Gio-2.0/Public/Application.cs
src/Tests/Libs/GLib-2.0.Tests/SynchronizationContextTest.cs

Closes #854
No unit tests yet. Need some feedback before adding a unit tests.

Implement SynchronizationContext for GLib

---

src/Libs/Gdk-4.0/Public/Module.cs

This seems to be the logical place to do it since the startup error comes from GDK, and this also ensures it's done automatically without any extra steps to document for users.
This is wrapped in a check for whether we're running on Windows, to avoid warnings from the `SupportedOSPlatform` attribute on `SetApartmentState()`
I've tested on Windows with `Samples/Gtk-4.0/Window` and verified that this works
Fixes: #864

Set the main thread's apartment state when initializing GDK

---

src/Generation/GirLoader/Input/Callback.cs
src/Generation/GirLoader/Output/Callback.GirModel.cs
src/Generation/GirLoader/Output/Callback.cs
src/Generation/GirLoader/Output/CallbackFactory.cs
src/Generation/GirLoader/Output/Constructor.GirModel.cs
src/Generation/GirLoader/Output/Function.GirModel.cs
src/Generation/GirLoader/Output/Method.GirModel.cs
src/Generation/GirLoader/PlatformSupport/Callbacks/Callback.GirModel.cs
src/Generation/GirLoader/PlatformSupport/Functions/Function.GirModel.cs
src/Generation/GirModel/Callable.cs
src/Generation/GirModel/Callback.cs
src/Generation/GirModel/Constructor.cs
src/Generation/GirModel/Function.cs
src/Generation/GirModel/Method.cs

- Support throws attribute for callbacks
- Make a `GirModel.Callback` a `GirModel.Callable`

Improve callback model

---

src/Generation/Generator/Renderer/Internal/Parameter/Converter/PointerGLibPtrArray.cs
src/Generation/GirModel/AnyType.cs

The generic parameter is not needed as the content of the array is not relevant as long as it is rendered as IntPtr. As there are GLib pointer arrays with types different from GirModel.Pointer this adds support for those cases, too.

Generalize GLib pointer array handling

---

src/Generation/Generator/Renderer/Public/Parameter/Converter/RecordArray.cs

The current code for record arrays is not really usable as the GetDirection method can return "ref" / "out" keywords which is not useful in context of native interop.
As HarfBuzz added a function containing a caller allocated out record this case is treated as a regular array to avoid compilation errors. During runtime this is expected to fail but was not working before either.

Workaround record array problem

---

src/Libs/Gtk-4.0/Public/FileDialog.cs
src/Libs/Gtk-4.0/Public/FileLauncher.cs
src/Libs/Gtk-4.0/Public/UriLauncher.cs

Added:
- Gtk.FileDialog.OpenAsync
- Gtk.FileDialog.SaveAsync
- Gtk.FileDialog.SelectFolderAsync
- Gtk.FileLauncher.LaunchAsync
- Gtk.FileLauncher.OpenContainingFolderAsync
- Gtk.UriLauncher.LaunchAsync
~~I don't think that throwing an exception on error like it's done in [`WebView`](https://github.com/gircore/gir.core/blob/main/src/Libs/WebKit-6.0/Public/WebView.cs) is desired behavior, error is set even if a dialog was simply cancelled by the user, which is definitely not a critical error and I think just checking for `null`/`false` makes more sense:~~
Related: #900

Add manual bindings for async functions

---

.github/workflows/ci.yml
src/Tests/Libs/Cairo-1.0.Tests/ContextTest.cs
src/Tests/Libs/Cairo-1.0.Tests/FontFaceTest.cs
src/Tests/Libs/Cairo-1.0.Tests/FontOptionsTest.cs
src/Tests/Libs/Cairo-1.0.Tests/ImageSurfaceTest.cs
src/Tests/Libs/Cairo-1.0.Tests/MatrixTest.cs
src/Tests/Libs/Cairo-1.0.Tests/PatternTest.cs
src/Tests/Libs/Cairo-1.0.Tests/ScaledFontTest.cs
src/Tests/Libs/GLib-2.0.Tests/FunctionTest.cs
src/Tests/Libs/GLib-2.0.Tests/Records/DirTest.cs
src/Tests/Libs/GLib-2.0.Tests/Records/ExceptionTest.cs
src/Tests/Libs/GLib-2.0.Tests/Records/UnownedHandleTest.cs
src/Tests/Libs/GLib-2.0.Tests/Records/VariantTest.cs
src/Tests/Libs/GLib-2.0.Tests/Records/VariantTypeTest.cs
src/Tests/Libs/GLib-2.0.Tests/SynchronizationContextTest.cs
src/Tests/Libs/GObject-2.0.Tests/Classes/ParamSpecTest.cs
src/Tests/Libs/GObject-2.0.Tests/Records/TypeTest.cs
src/Tests/Libs/GObject-2.0.Tests/Records/ValueTest.cs
src/Tests/Libs/GdkPixbuf-2.0.Tests/MemoryManagementTest.cs
src/Tests/Libs/GdkPixbuf-2.0.Tests/PropertyTest.cs

Enable unit tests on more platforms

---

src/Tests/Libs/GirTest-0.1.Tests/AliasTest.cs
src/Tests/Libs/GirTest-0.1.Tests/BitfieldTest.cs
src/Tests/Libs/GirTest-0.1.Tests/ByteArrayTest.cs
src/Tests/Libs/GirTest-0.1.Tests/IntegerArrayTest.cs

Inheriting from "Test" ensures that the garbage collector collects all obsolete objects which can reveal memory problems.

Add missing inheritence from Test class

---

src/Generation/Generator/Renderer/Public/Constructor/ConstructorRenderer.cs
src/Libs/GLib-2.0/Public/Bytes.cs
src/Native/GirTestLib/girtest-byte-array-tester.c
src/Native/GirTestLib/girtest-byte-array-tester.h
src/Tests/Libs/GirTest-0.1.Tests/ByteArrayTest.cs

Supporting array length parameters in public constructors actually means to not render them as they are handled internally.

Support array length parameters in public constructors

---

src/Libs/Gdk-4.0/Public/Clipboard.cs
src/Libs/Gtk-4.0/Public/AlertDialog.cs
src/Libs/Gtk-4.0/Public/FileDialog.cs

Added:
* `Gdk.Clipboard.ReadTextAsync`
* `Gtk.AlertDialog.ChooseAsync`
* `Gtk.FileDialog.OpenMultipleAsync`
* `Gtk.FileDialog.SelectMultipleFoldersAsync`
Related: #900

Add more manual bindings for async functions

---

src/Generation/Generator/Renderer/Internal/Parameter/Converter/PlatformStringArray.cs
src/Generation/Generator/Renderer/Internal/Parameter/Converter/Utf8StringArray.cs
src/Generation/Generator/Renderer/Internal/ParameterToManagedExpression/Converter/PlatformStringArray.cs
src/Generation/Generator/Renderer/Internal/ParameterToManagedExpression/Converter/Utf8StringArray.cs
src/Generation/Generator/Renderer/Internal/ReturnType/Converter/PlatformStringArray.cs
src/Generation/Generator/Renderer/Internal/ReturnType/Converter/Utf8StringArray.cs
src/Generation/Generator/Renderer/Public/ParameterToNativeExpression/Converter/PlatformStringArray.cs
src/Generation/Generator/Renderer/Public/ParameterToNativeExpression/Converter/Utf8StringArray.cs
src/Generation/Generator/Renderer/Public/ReturnTypeToManagedExpression/Converter/PlatformStringArray.cs
src/Generation/Generator/Renderer/Public/ReturnTypeToManagedExpression/Converter/Utf8StringArray.cs
src/Generation/GirLoader/Input/ArrayType.cs
src/Generation/GirLoader/Output/TypeReferenceFactory.cs

As zero terminated string arrays require a certain memory layout (NULL at the end) there could be a problem if a method has an array parameter which is zero terminated and length based at the same time. Preferring zero terminated rendering ensures that the memory layout fulfills the requirements.
Additionally this fixes a bug that the zero terminated flag was never actively set as bool.TryParse can't parse "0" or "1" but the serializer does.

Prefer zero terminated string array over length based arrays.

---

src/Generation/Generator/Fixer/Record/PublicMethodsColldingWithPropertiesFixer.cs
src/Generation/Generator/Fixer/Records.cs
src/Generation/Generator/Renderer/Internal/Field/Converter/String.cs
src/Generation/Generator/Renderer/Internal/TypedRecordHandle.cs
src/Generation/Generator/Renderer/Public/Field/Converter/Bitfield.cs
src/Generation/Generator/Renderer/Public/Field/Converter/Enumeration.cs
src/Generation/Generator/Renderer/Public/Field/Converter/PrimitiveValueType.cs
src/Generation/Generator/Renderer/Public/Field/Converter/String.cs
src/Generation/Generator/Renderer/Public/Field/FieldConverter.cs
src/Generation/Generator/Renderer/Public/Field/Fields.cs
src/Generation/Generator/Renderer/Public/Field/RenderableField.cs
src/Generation/Generator/Renderer/Public/TypedRecord.cs
src/Libs/GLib-2.0/Public/GException.cs
src/Native/GirTestLib/girtest-typed-record-tester.c
src/Native/GirTestLib/girtest-typed-record-tester.h
src/Tests/Libs/GirTest-0.1.Tests/TypedRecordTest.cs

TypedRecord: Add field access

---

src/Generation/Generator/Model/TypedRecord.cs
src/Generation/Generator/Renderer/Public/ParameterToNativeExpression/Converter/PointerAlias.cs
src/Generation/Generator/Renderer/Public/TypedRecord.cs
src/Tests/Libs/GirTest-0.1.Tests/TypedRecordTest.cs

Typed Record: Add parameterless constructor

---

src/Libs/GObject-2.0/Internal/ObjectMapper.ToggleRef.cs

RemoveToggleRef is not guaranteed to be thread safe as it is unknown what happens on the final object disposal (dependeing on the library using GObject).
As the dotnet GC is collecting it's garbage in a separate thread this can lead to side effects like the one described in #1044 where GTK is requiring the object disposal to happen on the main thread.
To fix this object disposal is tunneled through the main context of GLib.

ToggleRef: Remove toggle ref on main context

---

src/Generation/Generator/Renderer/Public/ParameterToNativeExpression/Converter/Class.cs
src/Generation/Generator/Renderer/Public/ParameterToNativeExpression/Converter/Interface.cs
src/Native/GirTestLib/girtest-class-tester.c
src/Native/GirTestLib/girtest-class-tester.h
src/Tests/Libs/GirTest-0.1.Tests/ClassTest.cs

Handle parameter ownership transfer for interfaces

---

docs/docs/faq.md
docs/docs/use.md
docs/toc.yml
src/GirCore.sln
src/Libs/GObject-2.0/Public/Object.cs

Remove INotifyPropertyChanged

---

src/Generation/Generator/Renderer/Public/ReturnTypeToManagedExpression/Converter/ForeignTypedRecord.cs
src/Generation/Generator/Renderer/Public/ReturnTypeToManagedExpression/Converter/Interface.cs
src/Generation/Generator/Renderer/Public/ReturnTypeToManagedExpression/Converter/OpaqueTypedRecord.cs
src/Generation/Generator/Renderer/Public/ReturnTypeToManagedExpression/Converter/OpaqueUntypedRecord.cs
src/Generation/Generator/Renderer/Public/ReturnTypeToManagedExpression/Converter/TypedRecord.cs
src/Generation/Generator/Renderer/Public/ReturnTypeToManagedExpression/Converter/UntypedRecord.cs

This is a minor tidy up to the generated code. Some of the expressions returned from `ReturnTypeConverter` implementations added a semicolon, but a semicolon is already added everywhere `ReturnTypeToManagedExpression.Render` is called.
This didn't cause any build failures but Rider would show red lines when viewing the generated code and complain about "unreachable code", referring to the empty statement before the second semicolon.

Remove duplicate semicolon in return statements

---

src/Generation/Generator/Model/Type.cs
src/Generation/Generator/Renderer/Public/Constant/Converter/PrimitiveValueType.cs
src/Generation/Generator/Renderer/Public/Constant/Converter/PrimitiveValueTypeAlias.cs
src/Generation/GirLoader/Output/NativeInteger.cs
src/Generation/GirLoader/TypeReferenceResolver/TypeReferenceResolver.GlobalTypeCache.cs
src/Generation/GirModel/NativeInteger.cs
src/Tests/Generation/GirLoader.Tests/ClassPropertyTest.cs
src/Tests/Libs/GirTest-0.1.Tests/ByteArrayTest.cs
src/Tests/Libs/GirTest-0.1.Tests/IntegerArrayTest.cs

The GObject type "gssize" (sgined "gsize") was mapped to "long". Which is wrong, as "gssize" is dependent if the system is a 64 bit / 32 bit host. This maps "gssize" to "nint", similarly to "gsize" which is already mapped to "nuint".

Map "gssize" to native integers

---

src/Generation/Generator/Renderer/Internal/Parameter/Converter/Utf8StringArray.cs
src/Native/GirTestLib/girtest-string-array-tester.c
src/Native/GirTestLib/girtest-string-array-tester.h
src/Tests/Libs/GirTest-0.1.Tests/StringArrayTest.cs

This fixes #1077
I'm not super familiar with the code so let me know if there's a better way to handle this, or if you'd rather just fix it yourself :smile:

Add nullable annotation to nullable string array parameters in internal methods

---

src/Generation/GirTool/GenerateCommand.cs

This fixes #1084
I couldn't see a good way to test this change, it would probably need a separate GitHub action job to generate code for a subset of the libraries which seems pretty heavy handed, but let me know if you think that's necessary or there's a better way.

Disable rendering code for repositories only required via includes

---

docs/docs/faq.md

- addresses #1083 
- I explained how to fix `System.DllNotFoundException` by calling `Module.Initialize()`
- separated the explanation of `System.DllNotFoundException` being thrown when a custom build binary is used from the details of how to use a custom binary build.

documenting System.DllNotFoundException troubleshooting

---

readme.md

Readme: Update status

---

src/Generation/Generator/Renderer/Internal/ForeignTypedRecordHandle.cs
src/Libs/cairo-1.0/Internal/ContextHandle.cs
src/Libs/cairo-1.0/Internal/DeviceHandle.cs
src/Libs/cairo-1.0/Internal/FontFaceHandle.cs
src/Libs/cairo-1.0/Internal/FontOptionsHandle.cs
src/Libs/cairo-1.0/Internal/PatternHandle.cs
src/Libs/cairo-1.0/Internal/RegionHandle.cs
src/Libs/cairo-1.0/Internal/ScaledFontHandle.cs
src/Libs/cairo-1.0/Internal/SurfaceHandle.cs

As foreign typed records are known to the gobject type system there must be a function available to free the instance. It is preferred to call this function directly as the type system has to do a dictionary lookup each time an instance should be freed.

Foreign typed records: Require to implement a handle release manually

---

src/Libs/cairo-1.0/Internal/SurfaceHandle.cs
src/Libs/cairo-1.0/Public/ImageSurface.cs
src/Libs/cairo-1.0/Public/Surface.cs

ImageSurface: Support memory pressure

---

src/Libs/GLib-2.0/GObject/Public/Type.cs

This improves performance as a generated equality function is used instead of a runtime check and allows for further compiler optimizations.

GObject.Type: Mark struct as readonly and make it a record

---

src/Libs/GObject-2.0/Internal/ObjectMapper.ToggleRef.cs
src/Libs/GObject-2.0/Internal/ObjectMapper.ToggleRegistration.cs
src/Libs/GObject-2.0/Internal/ObjectMapper.cs

Object: Fix ToggleNotify called after callback is disposed

---

docs/docs/tutorial/gtk/src/BoxLayout/BoxLayout.csproj
docs/docs/tutorial/gtk/src/HelloWorld/HelloWorld.csproj

By using project references it can be ensured that the tutorial code is working with the current code and must not be kept up to date after a version got released.
Fixes: #1145

Tutorial: Use project reference instead of package reference

---

src/Extensions/GObject-2.0.Integration/GObject-2.0.Integration.csproj

GObject-2.0.Integration: Disable snupk generation as there are no symbols which results in an error if the empty snupkg file is uploaded to nuget.

GObject-2.0.Integration: Disable snupk generation

---

src/Libs/GObject-2.0/Public/Object.cs
src/Tests/Libs/GirTest-0.1.Tests/ClassTest.cs

The virtual keyword got lost by accident during the implementation of the new instantiation framework. Custom classes want to be able to plug into the "Dispose" call of GObject.Object otherwise the custom "Dispose" would eventually not be executed if the method is marked with the "new" keyword.

GObject.Object: Make "Dispose" method virtual again

---

src/Generation/Generator/Renderer/Internal/TypedRecordHandle.cs
src/Generation/Generator/Renderer/Public/OpaqueTypedRecord.cs
src/Generation/Generator/Renderer/Public/TypedRecord.cs
src/Libs/GObject-2.0/Internal/ClosureHandle.cs
src/Libs/GObject-2.0/Public/Closure.cs

The "OnDispose" method was only called if a user explicitly called "Dispose()". If an object got collected via the GC the "OnDispose" method was not called, which is probably not what a user would expect.
Therefore, the "OnDispose" method got replaced by an "OnReleaseHandle" method for typed records which gets always called if a typed record gets freed.
This affects the debug message of a closure which indicates the collection of a closure if GirCore is compiled in debug mode.

TypedRecords: Remove public OnDispose method

---

src/Generation/Generator/Fixer/Record/PropertyNamedLikeRecordFixer.cs
src/Generation/Generator/Fixer/Records.cs
src/Generation/Generator/Model/Field.cs

e.g. Length.Length using PropertyNamedLikeRecordFixer

Add fixer for record-field name collision

---

src/Libs/GObject-2.0/Public/Value.cs
src/Native/GirTestLib/girtest-property-tester.c
src/Tests/Libs/GirTest-0.1.Tests/PropertyTest.cs

As bug #1258 notes, we also should set up tests for `long` values as well
Bug: #1257

Add missing support for ulong in GObject.Value to fix property accessors

---

src/Libs/GObject-2.0/Internal/DynamicInstanceFactory.cs
src/Libs/GObject-2.0/Internal/InstanceWrapper.cs

Prevents accidental use of DynamicInstanceFactory and InstanceWrapper for types that are not objects/classes, such as records. Records should use BoxedWrapper instead to wrap handles.
Closes #1315

Add GObject.Object to generic type constraint of instance factory/wrapper

---

src/Libs/GLib-2.0/Public/SList.Enumerator.cs
src/Libs/GLib-2.0/Public/SList.cs
src/Libs/GLib-2.0/Public/SListElement.cs
src/Libs/GLib-2.0/Public/SListExtensions.cs
src/Libs/GObject-2.0/Internal/DynamicInstanceFactory.cs
src/Libs/GObject-2.0/Internal/InstanceWrapper.cs
src/Libs/GObject-2.0/Public/SListExtensions.cs
src/Tests/Libs/GLib-2.0.Tests/Classes/SListTest.cs
src/Tests/Libs/GObject-2.0.Tests/Extensions/SListTest.cs

GLib.SList: Add enumerator and extension methods for element conversion
SList.Enumerator allows enumerating the list data with `IEnumerable<SListElement>` and with foreach loops.
The extension methods on `IEnumerable<SListElement>` allow conversion to object/boxed record instances or strings.
Includes unit tests.
* `ToBoxed` and `ToObject` are extension methods as part of GObject. They need access to the type system for wrapping the right handles.
* `ToStringUTF8` is used for UTF-8 string pointer data.
* Use `AsBoxed`, `AsObjects` and `AsStringsUTF8` for enumeration on a foreach loop.
Part of #588

GLib.SList: Add IEnumerable<SListElement> and related extensions

---

src/Generation/Generator/Renderer/Internal/Parameter/Converter/TypedRecord.cs
src/Generation/Generator/Renderer/Public/Parameter/Converter/TypedRecord.cs
src/Generation/Generator/Renderer/Public/ParameterToNativeExpression/Converter/TypedRecord.cs
src/Native/GirTestLib/girtest-typed-record-tester.c
src/Native/GirTestLib/girtest-typed-record-tester.h
src/Tests/Libs/GirTest-0.1.Tests/TypedRecordTest.cs

* Only non-nullable out parameters without ownership transfer for now
* Nullable out-parameters don't make much sense in C# in the traditional way
* Added new native test
* Fixed a few typos
See #1120, #1191 and #932 to see what part of them is solved by this.

Generate methods with typed records as out parameter (non-nullable, no transfer)
