gircore/gir.core

- Build/Program.cs
- Build/Projects.cs
- Build/Targets.cs
- README.md
- azure-pipelines.yml
> Build samples

- Libs/GObject/Core/Classes/Closure.IDisposable.cs
- Libs/GObject/Core/Classes/Closure.cs
- Libs/GObject/Core/Classes/Object.Properties.cs
- Libs/GObject/Core/Classes/Object.cs
- Libs/GObject/Wrapper/API/Value.cs
- Libs/Handy/Core/Classes/Paginator.cs
> Remove implicit casts

- Libs/Gtk3/Classes/Global.cs
- Samples/Gtk3/QuickStart/Program.cs
Expands and fleshes out the quick start demo a bit. Also adds plenty of comments explaining the basics of Gir.Core. This could be expanded into a tutorial later down the line.
This was mostly to get back up to speed with signal generation. Not sure if `GenerateSignals` is the right place to merge this, but it depends on some recent changes there.
> QuickStart Demo

- Generator/Templates/GObject/global.sbntxt
- Libs/GObject/Classes/Object.TypeDictionary.cs
- Libs/GObject/Classes/Object.TypeIntegration.cs
- Libs/GObject/Classes/Object.cs
- Libs/GObject/Structs/Value.cs
- Libs/Gio/Classes/DBusConnection.cs
- Libs/Gst/Classes/Application.Static.cs
- Libs/Gst/Classes/Parse.cs
- Libs/Gtk3/Classes/Global.cs
> Global: Move native methods into nested internal class

- Build/Program.cs
- Libs/Gio/Classes/Application.cs
- Libs/Gtk3/Classes/Application.cs
- Libs/Gtk3/Classes/ApplicationWindow.cs
- Libs/Gtk3/Classes/Box.cs
- Libs/Gtk3/Classes/Builder.cs
- Libs/Gtk3/Classes/Connect.cs
- Libs/Gtk3/Classes/Dialog.cs
- Libs/Gtk3/Classes/Image.cs
- Libs/Gtk3/Classes/Widget.cs
- Libs/Gtk3/Classes/Window.cs
- Samples/Gtk3/GtkMinimal/DemoWindow.cs
- Samples/Gtk3/GtkMinimal/GtkMinimal.csproj
- Samples/Gtk3/GtkMinimal/Program.cs
> GtkMinimal: Reenable sample

- Generator/Generator.cs
This recursively registeres aliases from dependencies and propagates them to the dependant project. We need this for e.g. GStreamer, where `GstClockTime` (an alias for `ulong`) is defined in Gst but used in plugins.
The performance hit isn't too noticeable, especially compared to building GStreamer plugins (which almost double generation time). We'll get something like this for free with the generator architecture I proposed in https://github.com/gircore/gir.core/issues/100#issuecomment-721087887, so this is more of a temporary workaround while we figure out how interfaces should work.
> Generator: Alias Propagation

- Libs/GObject/Classes/Object.TypeDictionary.cs
In addition to recursively registering types when a lookup fails, we also want to cache the failed query so that future lookups only need a simple dictionary lookup, rather than the more expensive fuzzy assembly search procedure. This change optimises the existing lookup to only run once per (failed) type, rather than every time we perform a lookup.
Specifically:
- This PR allows the typedict to add one way aliases between GTypes and Types so one C# object can represent both a GObject, and its descendant types.
- On repeat lookup, the alias is used to resolve the type rather than an assembly search.
- For example, we want `GdkWin32Screen`, `GdkX11Screen`, `GdkWaylandScreen`, etc to all alias to `Gdk.Screen`
- If we wrapped the private platform APIs in the future, they would resolve …
> TypeDict: Cache fallback type queries

- Generator/Templates/GLib/struct_as_class.sbntxt
- Libs/GLib/Classes/Bytes.cs
- Libs/GLib/Classes/MainContext.cs
- Libs/GLib/Classes/MainLoop.cs
- Libs/GLib/Classes/Variant.IDisposable.cs
- Libs/GLib/Classes/Variant.cs
- Libs/GLib/Classes/VariantType.cs
- This hides the native GLib methods from public API
> GLib: Add internal Native class

- .github/workflows/ci.yml
- Build/Program.cs
- Build/Projects.cs
- Build/Settings.cs
- Build/Targets/Generate.cs
- Generator/Generator.cs
- Generator/Services/Writer/WriteClassService.cs
- Generator/Services/Writer/WriterService.cs
- Generator/Templates/class.methods.sbntxt
- README.md
- Tests/Build.Tests/RunnerTest.cs
An attempt to get the new generator passing CI with method generation on-by-default.
~Not a draft only so CI will run - still a work in progress~
**Edit:** CI back up and running!
> Generator CI

- Build/Projects.cs
- Libs/GstPbutils-1.0/Classes/Global.cs
- Libs/GstVideo-1.0/Interfaces/Navigation.cs
- Repository/Converter/IdentifierConverter.cs
- Repository/Factories/Model/ConstantFactory.cs
- Repository/Factories/Model/FieldFactory.cs
- Repository/Factories/Model/InstanceParameterFactory.cs
- Repository/Factories/Model/MemberFactory.cs
- Repository/Factories/Model/MethodFactory.cs
- Repository/Factories/Model/SingleParameterFactory.cs
Gets GStreamer plugins building with the new generator (GstAudio/GstVideo/GstPbutils)
> GStreamer for New Generator

- .github/workflows/ci.yml
Keeps current behaviour on Linux (Unit/Integration Tests). Does unit testing only on Windows and Mac.
> Setup Matrix Build (for Windows/MacOS)

- src/Libs/GObject-2.0/Records/Value.cs
> Do not create a Value handle which can not be disposed

- src/Generation/Generator3/Converter/Model/ParameterConverter.ToManaged.cs
- src/Generation/Generator3/Generation/Record/InternalManagedHandle/InternalManagedHandleTemplate.cs
- src/Generation/Generator3/Generation/Record/InternalSafeHandle/InternalSafeHandleTemplate.cs
- src/Generation/Generator3/Generation/Record/PublicClass/PublicClassTemplate.cs
- src/Libs/GLib-2.0/Records/MainLoop.cs
- src/Libs/GObject-2.0/Internal/Classes/BoxedWrapper.cs
- src/Libs/GObject-2.0/Internal/Classes/ObjectWrapper.cs
- src/Libs/GObject-2.0/Records/Value.cs
- src/Libs/Gdk-3.0/Records/Event.cs
- src/Libs/Gtk-3.0/Classes/TreeSelection.cs
- src/Samples/Gtk3/DrawingArea/DrawingArea.cs
> SafeHandles: Support owned / unowned refs

- src/Generation/Generator3/Bitfields.cs
- src/Generation/Generator3/Callbacks.cs
- src/Generation/Generator3/Classes.cs
- src/Generation/Generator3/Constants.cs
- src/Generation/Generator3/Enumerations.cs
- src/Generation/Generator3/Functions.cs
- src/Generation/Generator3/Interfaces.cs
- src/Generation/Generator3/Records.cs
- src/Generation/Generator3/Unions.cs
- src/Generation/GirLoader/Output/Class.cs
Allows for GLib to generate again
> Fix Type Matcher

- src/Generation/Generator3/Generation/Class/Standard/PublicFramework/ParentConstructors.cs
- src/Generation/Generator3/Generation/Class/Standard/PublicFramework/PublicFrameworkModel.cs
- src/Libs/GObject-2.0/Classes/Object.cs
- src/Libs/Gtk-3.0/Classes/Application.cs
> Do not free unowned memory

- src/GirCore.Testing.props
- Bump FluentAssertions to 6.5.1
- Bump coverlet.collector to 3.1.2
> Update test dependencies

- src/GenerateLibs.fsx
This introduces platform specific gir files. With this commit only the linux gir files are used.
> Update gir-files repository

- src/Libs/cairo-1.0/Records/TextExtents.cs
- src/Samples/Gtk3/TextEditor/Application/DocumentView.cs
- src/Samples/Gtk3/TextEditor/Application/PieceTableDisplay.cs
> Use PascalCase for Cairo.TextExtents fields

- .github/workflows/update-gir-files.yml
- src/GirCore.sln
> Automatically update gir files

- src/Libs/cairo-1.0/Internal/Records/Context.Transformations.cs
- src/Libs/cairo-1.0/Records/Context.Transformations.cs
- src/Tests/Libs/Cairo-1.0.Tests/ContextTest.cs
This adds the bindings for https://cairographics.org/manual/cairo-Transformations.html
> Add Cairo.Context bindings for transformation-related methods

- src/Libs/cairo-1.0/Internal/Records/Matrix.cs
- src/Libs/cairo-1.0/Records/Matrix.cs
- src/Tests/Libs/Cairo-1.0.Tests/MatrixTest.cs
This adds the bindings from https://cairographics.org/manual/cairo-cairo-matrix-t.html
> Add bindings for Cairo.Matrix methods

- src/Generation/Generator3/Generator3.csproj
- src/GirCore.Testing.props
- src/Integration/Integration.csproj
- Microsoft.CodeAnalysis.CSharp 4.2.0
- Microsoft.NET.Test.Sdk 17.2
- FluentAssertions 6.7.0
- Moq 4.18.1
> Bump several nuget packages to their newest version:

- src/Generation/Generator3/Renderer/Public/Member.cs
this fixes generating enums in different user locales
closes #648
> Changed member generation formatting to use invariant culture

- src/Tests/Libs/Gtk-3.0.Tests/PropertyTests.cs
> Add test to explicitly check setting nullable properties

- src/Libs/Pango-1.0/Pango-1.0.csproj
> Update gir files

- src/Libs/Atk-1.0/Atk-1.0.csproj
- src/Libs/GLib-2.0/GLib-2.0.csproj
- src/Libs/GObject-2.0/GObject-2.0.csproj
- src/Libs/Gdk-3.0/Gdk-3.0.csproj
- src/Libs/Gdk-4.0/Gdk-4.0.csproj
- src/Libs/GdkPixbuf-2.0/GdkPixbuf-2.0.csproj
- src/Libs/Gio-2.0/Gio-2.0.csproj
- src/Libs/Graphene-1.0/Graphene-1.0.csproj
- src/Libs/Gsk-4.0/Gsk-4.0.csproj
- src/Libs/Gst-1.0/Gst-1.0.csproj
- src/Libs/GstAudio-1.0/GstAudio-1.0.csproj
- src/Libs/GstBase-1.0/GstBase-1.0.csproj
- src/Libs/GstPbutils-1.0/GstPbutils-1.0.csproj
- src/Libs/GstVideo-1.0/GstVideo-1.0.csproj
- src/Libs/Gtk-3.0/Gtk-3.0.csproj
- src/Libs/Gtk-4.0/Gtk-4.0.csproj
- src/Libs/HarfBuzz-0.0/HarfBuzz-0.0.csproj
- src/Libs/Pango-1.0/Pango-1.0.csproj
- src/Libs/PangoCairo-1.0/PangoCairo-1.0.csproj
- src/Libs/cairo-1.0/cairo-1.0.csproj
This includes the version of a library in it's package id which allows to support different major versions per library.
Fixes #39
> Update package id

- readme.md
- src/GirCore.Publishing.props
- src/GirCore.sln
- src/Libs/Directory.Build.props
- src/NugetReadme.md
- Add package tags
- Add package readme
- Set project url
- Correct repository url
Fixes #673
> Improve nuget metadata

- src/Generation/Generator/Fixer/Bitfield/DisableDuplicateMembersFixer.cs
- src/Generation/Generator/Fixer/Bitfields.cs
- src/Generation/Generator/Fixer/Class/InterfaceMethodsCollidingWithClassMethodsFixer.cs
- src/Generation/Generator/Fixer/Class/InternalMethodsNamedLikeClassFixer.cs
- src/Generation/Generator/Fixer/Class/PropertyLikeInterfacePropertyFixer.cs
- src/Generation/Generator/Fixer/Class/PropertyNamedLikeClassFixer.cs
- src/Generation/Generator/Fixer/Class/PublicMethodsColldingWithPropertiesFixer.cs
- src/Generation/Generator/Fixer/Classes.cs
- src/Generation/Generator/Fixer/Fixer.cs
- src/Generation/Generator/Fixer/Namespace.cs
- src/Generation/Generator/Fixer/Namespace/DisableRecordsConflictingWithGObjectsFixer.cs
- src/Generation/Generator/Fixer/Record/InternalMethodsNamedLikeRecordFixer.cs
- src/Generation/Generator/Fixer/Records.cs
> Split fixers into several classes

- src/Extensions/Gtk-4.0.DependencyInjection/Gtk-4.0.DependencyInjection.csproj
- src/GirCore.Testing.props
- src/Samples/Gtk-4.0/DependencyInjection/DependencyInjection.csproj
- FluentAssertions to 6.8.0
- Microsoft.NET.Test.Sdk to 17.4.1
- MSTest.TestAdapter to 3.0.0
- MSTest.TestFramework to 3.0.0
- coverlet.collector to 3.2.0
- Moq to 4.18.3
- Microsoft.Extensions.DependencyInjection.Abstractions to 7.0.0
- Microsoft.Extensions.DependencyInjection to 7.0.0
> Update nuget packages

- src/Libs/GObject-2.0/Public/Closure.cs
> Closure: Handle null pointer for return value

- src/Libs/GObject-2.0/Internal/Functions.cs
- src/Libs/GObject-2.0/Public/Value.cs
> Move StrvGetType into internal namespace

- src/Generation/Generator/Renderer/Public/Class/ClassConstructors.cs
> Fix overusing of new keyword

- src/Generation/Generator/Renderer/Public/ParameterToNativeExpression/Converter/Class.cs
When there is an ownership transfer, the reference count is now incremented before calling the method
Fixes: #783
> Handle ownership transfer for GObject parameters

- docs/docs/apps.md
> Apps - Add Tube Converter

- src/Libs/GLib-2.0/Public/MainLoop.cs
- src/Libs/GLib-2.0/Public/Source.cs
> Manual GLib implementations

- src/Generation/Generator/Renderer/Internal/Parameter/Converter/Bitfield.cs
- src/Generation/Generator/Renderer/Public/Parameter/Converter/Bitfield.cs
- src/Generation/Generator/Renderer/Public/ParameterToNativeExpression/Converter/Bitfield.cs
- src/Native/GirTestLib/girtest-bitfield-tester.c
- src/Native/GirTestLib/girtest-bitfield-tester.h
- src/Native/GirTestLib/girtest.h
- src/Native/GirTestLib/meson.build
- src/Tests/Libs/GirTest-0.1.Tests/BitfieldTest.cs
> Support pointed bitfields

- docs/docs/apps.md
> Apps - Rename Tube Converter, add Tagger and Cavalier

- src/Libs/GObject-2.0/Public/Object.Registration.cs
- src/Tests/Libs/GObject-2.0.Tests/Classes/GenericTypeRegistrationTests.cs
> Fix generic gobject types

- .github/workflows/ci.yml
- src/GirCore.Libs.slnf
- src/GirCore.sln
> Fix slnf file

- src/Libs/GLib-2.0/GLib-2.0.csproj
- src/Libs/GLib-2.0/Internal/BoxedHandle.cs
- src/Libs/GLib-2.0/Internal/Functions.cs
- src/Libs/GLib-2.0/Internal/NativeGTypeProvider.cs
- src/Libs/GLib-2.0/Internal/NativeGTypeProviderHelper.cs
- src/Libs/GLib-2.0/Public/Module.cs
- src/Libs/GObject-2.0/Internal/Functions.cs
> Integrate glib gobject

- src/Generation/Generator/Renderer/Public/Class/ClassConstructors.cs
- src/Generation/Generator/Renderer/Public/Constructor/ConstructorConverter.cs
- src/Generation/Generator/Renderer/Public/Constructor/ConstructorData.cs
- src/Generation/Generator/Renderer/Public/Constructor/ConstructorRenderer.cs
- src/Generation/Generator/Renderer/Public/Constructor/Converter/Class.cs
- src/Generation/GirLoader/Output/ClassFactory.cs
- src/Generation/GirLoader/Output/Constructor.GirModel.cs
- src/Generation/GirLoader/Output/Constructor.cs
- src/Generation/GirLoader/Output/InterfaceFactory.cs
- src/Generation/GirLoader/Output/RecordFactory.cs
- src/Generation/GirModel/Constructor.cs
> Add constructor renderer

- src/Generation/Generator/Renderer/Public/FunctionRenderer.cs
- src/Generation/Generator/Renderer/Public/MethodRenderer.cs
- src/Generation/Generator/Renderer/Public/ParameterToNativeExpression/Converter/PrimitiveValueTypeArray.cs
- src/Generation/Generator/Renderer/Public/ParameterToNativeExpression/ParameterToNativeData.cs
- src/Native/GirTestLib/girtest-byte-array-tester.c
- src/Native/GirTestLib/girtest-byte-array-tester.h
- src/Tests/Libs/GirTest-0.1.Tests/ByteArrayTest.cs
> Support inout array length parameter

- src/Generation/Generator/Renderer/Public/InstanceParameterToNativeExpression/Converter/Class.cs
- src/Generation/Generator/Renderer/Public/InstanceParameterToNativeExpression/Converter/Interface.cs
- src/Generation/Generator/Renderer/Public/InstanceParameterToNativeExpression/Converter/Pointer.cs
- src/Generation/Generator/Renderer/Public/InstanceParameterToNativeExpression/InstanceParameterConverter.cs
- src/Generation/Generator/Renderer/Public/InstanceParameterToNativeExpression/InstanceParameterToNativeExpression.cs
- src/Generation/Generator/Renderer/Public/MethodRenderer.cs
This allows to create custom expressions per instance parameter type and additional properties like transfer information.
> Add InstanceParameterToNativeExpression

- src/Generation/Generator/Renderer/Internal/DocComments.cs
- src/Generation/Generator/Renderer/Internal/Methods.cs
> Render internal instance parameter information

- src/Libs/Adw-1/Public/Module.cs
- src/Libs/GLib-2.0/Public/Module.cs
- src/Libs/GObject-2.0/Public/Module.cs
- src/Libs/Gdk-4.0/Public/Module.cs
- src/Libs/GdkPixbuf-2.0/Public/Module.cs
- src/Libs/Gio-2.0/Public/Module.cs
- src/Libs/GirTest-0.1/Public/Module.cs
- src/Libs/Graphene-1.0/Public/Module.cs
- src/Libs/Gsk-4.0/Public/Module.cs
- src/Libs/Gst-1.0/Public/Module.cs
- src/Libs/GstAudio-1.0/Public/Module.cs
- src/Libs/GstBase-1.0/Public/Module.cs
- src/Libs/GstPbutils-1.0/Public/Module.cs
- src/Libs/GstVideo-1.0/Public/Module.cs
- src/Libs/Gtk-4.0/Public/Module.cs
- src/Libs/GtkSource-5/Public/Module.cs
- src/Libs/HarfBuzz-0.0/Public/Module.cs
- src/Libs/JavaScriptCore-6.0/Public/Module.cs
- src/Libs/Pango-1.0/Public/Module.cs
- src/Libs/PangoCairo-1.0/Public/Module.cs
- src/Libs/Soup-3.0/Public/Module.cs
- src/Libs/WebKit-6.0/Public/Module.cs
- src/Libs/WebKitWebProcessExtension-6.0/Public/Module.cs
- src/Libs/cairo-1.0/Public/Module.cs
> Make Module class static

- src/Samples/GdkPixbuf-2.0/TestLoading/TestLoading.csproj
- src/Samples/GdkPixbuf-2.0/TestMemoryLeaks/TestMemoryLeaks.csproj
Fixes #929  - "GdkPixbuf samples are not working"
>  Copy test image to output folder

- docs/docs/libraries.md
> Improve "Libraries" section description

- src/Generation/Generator/Renderer/Internal/ParameterToManagedExpression/Converter/Class.cs
- src/Native/GirTestLib/girtest-callback-tester.c
- src/Native/GirTestLib/girtest-callback-tester.h
- src/Tests/Libs/GirTest-0.1.Tests/CallbackTest.cs
> Fix nullable class parameters in callbacks

- docs/docs/use.md
> Refer to the API documentation

- src/Libs/Gio-2.0/Public/Application.cs
- src/Samples/Adw-1/Window/Program.cs
- src/Samples/Gtk-4.0/AboutDialog/Program.cs
- src/Samples/Gtk-4.0/Builder/Program.cs
- src/Samples/Gtk-4.0/DrawingArea/DrawingArea.cs
- src/Samples/Gtk-4.0/Window/Program.cs
- src/Samples/GtkSource-5/GtkSourceView/Program.cs
- src/Samples/WebKit-6.0/JavascriptCall/Program.cs
- src/Samples/WebKit-6.0/JavascriptCallback/Program.cs
> Add RunWithSynchronizationContext with arguments

- src/Generation/Generator/Renderer/Public/OpaqueTypedRecord.cs
- src/Tests/Libs/GirTest-0.1.Tests/OpaqueTypedRecordTest.cs
> Fix wrapping opaque typed records

- src/Libs/GObject-2.0/Public/Type.cs
- src/Libs/GObject-2.0/Public/Value.cs
- src/Tests/Libs/GObject-2.0.Tests/Records/ValueTest.cs
> GValue: Support setting a string array

- src/Generation/GirLoader/Input/Field.cs
- src/Generation/GirLoader/Output/Field.GirModel.cs
- src/Generation/GirLoader/Output/Field.cs
- src/Generation/GirLoader/Output/FieldFactory.cs
- src/Generation/GirModel/Field.cs
> GirModel: Add field writable property

- src/Generation/GirLoader/Input/Field.cs
- src/Generation/GirLoader/Output/Field.cs
> Make struct fields readable by default

- src/Libs/GObject-2.0/Public/Value.cs
- src/Tests/Libs/GObject-2.0.Tests/Records/ValueTest.cs
> GValue.GetStringArray: Ensure type before accessing data

- src/Libs/GObject-2.0/Public/Object.cs
- src/Libs/GObject-2.0/Public/Type.cs
> Small fixes

- src/Libs/GObject-2.0/Internal/ObjectWrapper.cs
- src/Native/GirTestLib/girtest-class-tester.c
- src/Native/GirTestLib/girtest-class-tester.h
- src/Tests/Libs/GirTest-0.1.Tests/ClassTest.cs
> Avoid marshalling of instance data

- src/Libs/GObject-2.0/Public/Value.cs
> Value: Avoid marshalling

- src/Generation/Generator/Model/Function.cs
- src/Generation/Generator/Renderer/Public/FunctionRenderer.cs
- src/Tests/Libs/Gtk-4.0.Tests/PropertyTests.cs
> Fix warnings

- src/Libs/GObject-2.0/Public/Property.cs
> Properties

- src/Tests/Libs/GLib-2.0.Tests/Records/VariantTest.cs
> Test: Add Variant test which uses VariantIter and VariantBuilder

- docs/docs/use.md
> Document how to handle DllNotFoundException

- src/Generation/Generator/Renderer/Public/ReturnTypeToManagedExpression/Converter/Class.cs
> Fundamental types: Support returning a null value

- src/Properties/GirCore.Testing.props
> Nuget: Update packages

- docs/docs/faq.md
- src/Libs/GObject-2.0/Public/Property.cs
- src/Tests/Libs/GirTest-0.1.Tests/PropertyTest.cs
> Property: Add Notify / Unnotify methods

- src/Libs/GObject-2.0/Internal/ObjectMapper.ToggleRef.cs
- src/Libs/GObject-2.0/Internal/ObjectMapper.cs
- src/Libs/GObject-2.0/Internal/TypeDictionary.cs
- src/Libs/GObject-2.0/Public/Object.cs
> Improve logging

- .github/workflows/ci.yml
> Update macos runner to version 14

- src/Libs/Gtk-4.0/Public/AlertDialog.cs
> Move ChooseAsync method to correct class

- src/Generation/Generator/Renderer/Public/Class/ClassFramework.cs
> Class: Add public constructor which support ConstructArguments

- docs/docs/tutorial/gtk/src/BoxLayout/BoxLayout.csproj
- docs/docs/tutorial/gtk/src/HelloWorld/HelloWorld.csproj
- src/Properties/GirCore.Publishing.props
> Do not publish tutorial projects

- src/Generation/GirLoader/Input/AnyType.cs
- src/Generation/GirModel/Function.cs
- src/Libs/GObject-2.0/Public/PropertyDefinition.cs
- src/Libs/Gtk-4.0/Public/Builder.cs
> Fix code format

- src/Extensions/GObject-2.0.Integration/SourceGenerator/Subclass/SubclassCode.cs
- src/Extensions/GObject-2.0.Integration/SourceGenerator/Subclass/SubclassData.cs
- src/Extensions/GObject-2.0.Integration/SourceGenerator/Subclass/SubclassValuesProvider.cs
- src/Tests/Libs/GirTest-0.1.Tests/SubclassIntegrationTest.GlobalNamespace.cs
- src/Tests/Libs/GirTest-0.1.Tests/SubclassIntegrationTest.cs
> GObject-2.0.Integration: Support global namespace

- src/Libs/Gtk-4.0/Public/AlertDialog.cs
- src/Libs/Gtk-4.0/Public/FileDialog.cs
- src/Libs/Gtk-4.0/Public/FileLauncher.cs
- src/Libs/Gtk-4.0/Public/FontDialog.cs
- src/Libs/Gtk-4.0/Public/UriLauncher.cs
Fixes https://github.com/gircore/gir.core/issues/1198
> Allow NULL parent window in async dialog functions

- build/GetVersion.fsx
- src/GirCore.sln
> Build: Add new F# script to determine current version number

- .github/workflows/release.yml
- scripts/GetVersion.fsx
- src/GirCore.sln
> Release: Automatically create Github release

- .github/workflows/release.yml
> Fix auto release

- .github/workflows/release.yml
> Auto release: Install github cli tool

- .github/workflows/release.yml
> Auto release: Add nuget packages

- .github/workflows/release.yml
> Auto release: fix nuget path

- .github/workflows/release.yml
> Auto release: List nuget files relative to source path

- src/Libs/GLib-2.0/Internal/MainLoopSynchronizationContext.cs
- src/Tests/Libs/GLib-2.0.Tests/SynchronizationContextTest.cs
> MainLoopSynchronizationContext: Implement Send

- properties/GirCore.Testing.props
- src/Tests/Libs/Directory.Build.props
- src/Tests/Libs/GObject-2.0.Tests/Records/ValueTest.cs
- src/Tests/Libs/GirTest-0.1.Tests/CLongTest.cs
- src/Tests/Libs/GirTest-0.1.Tests/CULongTest.cs
- src/Tests/Shared/PlatformConditionAttribute.cs
> Add and use in tests platform attribute

- docs/docs/apps.md
> Add Pinta, fixes #1233

- src/Libs/GObject-2.0/Public/Closure.cs
- src/Libs/GObject-2.0/Public/ReturningSignalTSender.cs
- src/Libs/GObject-2.0/Public/ReturningSignalTSenderTSignalArgs.cs
- src/Libs/GObject-2.0/Public/SignalTSender.cs
- src/Libs/GObject-2.0/Public/SignalTSenderTSignalArgs.cs
> Closure: Bind closure to object lifetime

- docs/docs/apps.md
> Remove Parabolic from App list

- src/Libs/GObject-2.0/Internal/ClosureHandle.cs
- src/Libs/GObject-2.0/Internal/ObjectHandle.cs
- src/Libs/GObject-2.0/Public/Closure.cs
- src/Libs/GObject-2.0/Public/ReturningSignalTSender.cs
- src/Libs/GObject-2.0/Public/ReturningSignalTSenderTSignalArgs.cs
- src/Libs/GObject-2.0/Public/SignalTSender.cs
- src/Libs/GObject-2.0/Public/SignalTSenderTSignalArgs.cs
- src/Tests/Libs/GirTest-0.1.Tests/SignalTest.cs
> Rework Closures

- properties/GirCore.Publishing.props
> Bump version to 0.7.0

- .github/workflows/ci.yml
> CI: Install github cli

- src/Generation/Generator/Model/PlatformStringArray.cs
- src/Generation/Generator/Model/Utf8StringArray.cs
- src/Generation/Generator/Renderer/Internal/Parameter/Converter/PlatformStringArray.cs
- src/Generation/Generator/Renderer/Internal/Parameter/Converter/Utf8StringArray.cs
- src/Generation/Generator/Renderer/Internal/ParameterToManagedExpression/Converter/PlatformStringArray.cs
- src/Generation/Generator/Renderer/Internal/ParameterToManagedExpression/Converter/Utf8StringArray.cs
- src/Generation/Generator/Renderer/Internal/ReturnType/Converter/PlatformStringArray.cs
- src/Generation/Generator/Renderer/Internal/ReturnType/Converter/Utf8StringArray.cs
- src/Generation/Generator/Renderer/Public/ParameterToNativeExpression/Converter/PlatformStringArray.cs
- src/Generation/Generator/Renderer/Public/ParameterToNativeExpression/Converter/Utf8StringArray.cs
- src/Generation/Generator/Renderer/Public/ReturnTypeToManagedExpression/Converter/PlatformStringArray.cs
- src/Generation/Generator/Renderer/Public/ReturnTypeToManagedExpression/Converter/Utf8StringArray.cs
- src/Generation/Generator/Renderer/Public/ReturnTypeToManagedExpression/ReturnTypeToManagedData.cs
- src/Libs/GLib-2.0/Internal/PlatformStringArrayNullTerminatedHandle.cs
- src/Libs/GLib-2.0/Internal/PlatformStringArraySizedHandle.cs
- src/Libs/GLib-2.0/Internal/Utf8StringArrayNullTerminatedHandle.cs
- src/Libs/GLib-2.0/Internal/Utf8StringArraySizedHandle.cs
- src/Native/GirTestLib/girtest-platform-string-array-null-terminated-tester.c
- src/Native/GirTestLib/girtest-platform-string-array-null-terminated-tester.h
- src/Native/GirTestLib/girtest-utf8-string-array-null-terminated-tester.c
- src/Native/GirTestLib/girtest-utf8-string-array-null-terminated-tester.h
- src/Tests/Libs/GirTest-0.1.Tests/PlatformStringArrayNullTerminatedTest.cs
- src/Tests/Libs/GirTest-0.1.Tests/Utf8StringArrayNullTerminatedTest.cs
> Improve size based string array support

- docs/docs/ecosystem.md
- docs/index.md
- docs/toc.yml
- src/GirCore.sln
> Add ecosystem page
